[2023-09-05T13:07:02.567+0000] {processor.py:157} INFO - Started process (PID=6154) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:02.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:02.569+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:02.569+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:02.572+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:02.571+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 16
    s
    ^
SyntaxError: positional argument follows keyword argument
[2023-09-05T13:07:02.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:02.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.028 seconds
[2023-09-05T13:07:03.603+0000] {processor.py:157} INFO - Started process (PID=6159) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:03.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:03.607+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:03.606+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:03.612+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:03.610+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 17
    ) as dag:
    ^
SyntaxError: invalid syntax
[2023-09-05T13:07:03.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:03.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.042 seconds
[2023-09-05T13:07:08.667+0000] {processor.py:157} INFO - Started process (PID=6164) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:08.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:08.669+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:08.669+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:08.673+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:08.672+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 16, in <module>
    schedule=da
NameError: name 'da' is not defined
[2023-09-05T13:07:08.674+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:08.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.036 seconds
[2023-09-05T13:07:11.736+0000] {processor.py:157} INFO - Started process (PID=6169) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:11.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:11.742+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:11.741+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:11.765+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:11.756+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 572, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 217, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: <class 'datetime.datetime'> is not a valid schedule_interval.
[2023-09-05T13:07:11.765+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:11.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.079 seconds
[2023-09-05T13:07:12.801+0000] {processor.py:157} INFO - Started process (PID=6180) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:12.803+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:12.805+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:12.805+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:12.828+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:12.821+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 572, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 217, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: datetime.datetime(2023, 9, 1, 0, 0) is not a valid schedule_interval.
[2023-09-05T13:07:12.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:12.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.077 seconds
[2023-09-05T13:07:21.940+0000] {processor.py:157} INFO - Started process (PID=6186) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:21.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:21.949+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:21.947+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:21.962+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:21.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 16
    schedule
    ^
SyntaxError: positional argument follows keyword argument
[2023-09-05T13:07:21.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:22.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.088 seconds
[2023-09-05T13:07:23.975+0000] {processor.py:157} INFO - Started process (PID=6191) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:23.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:23.976+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:23.976+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:23.979+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:23.978+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 17
    ) as dag:
    ^
SyntaxError: invalid syntax
[2023-09-05T13:07:23.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:23.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.024 seconds
[2023-09-05T13:07:26.000+0000] {processor.py:157} INFO - Started process (PID=6196) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:26.001+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:26.002+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.001+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:26.015+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:26.150+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.149+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:ganza_dag_v6
[2023-09-05T13:07:26.173+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.173+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:ganza_dag_v6
[2023-09-05T13:07:26.181+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.181+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:ganza_dag_v6
[2023-09-05T13:07:26.197+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.197+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:26.208+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.208+0000] {dag.py:2929} INFO - Creating ORM DAG for ganza_dag_v6
[2023-09-05T13:07:26.218+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.218+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-01T00:00:00+00:00, run_after=2023-09-02T00:00:00+00:00
[2023-09-05T13:07:26.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.239 seconds
[2023-09-05T13:07:33.129+0000] {processor.py:157} INFO - Started process (PID=6206) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:33.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:33.132+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:33.131+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:33.148+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:33.159+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:33.159+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:33.181+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:33.181+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:33.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.079 seconds
[2023-09-05T13:07:45.181+0000] {processor.py:157} INFO - Started process (PID=6218) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:45.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:45.183+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:45.183+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:45.196+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:45.211+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:45.211+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:45.246+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:45.245+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:45.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.103 seconds
[2023-09-05T13:07:47.344+0000] {processor.py:157} INFO - Started process (PID=6223) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:47.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:47.350+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:47.349+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:47.377+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:47.390+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:47.390+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:47.420+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:47.419+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:47.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.114 seconds
[2023-09-05T13:07:52.396+0000] {processor.py:157} INFO - Started process (PID=6228) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:52.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:52.398+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:52.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:52.421+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:52.441+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:52.440+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:52.472+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:52.472+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:52.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.102 seconds
[2023-09-05T13:08:09.664+0000] {processor.py:157} INFO - Started process (PID=6238) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:09.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:09.665+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:09.665+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:09.679+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:09.788+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:09.788+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:09.819+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:09.819+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:09.848+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.189 seconds
[2023-09-05T13:08:12.759+0000] {processor.py:157} INFO - Started process (PID=6243) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:12.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:12.760+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:12.760+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:12.771+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:12.782+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:12.781+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:12.812+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:12.811+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:12.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.078 seconds
[2023-09-05T13:08:16.794+0000] {processor.py:157} INFO - Started process (PID=6256) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:16.796+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:16.797+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:16.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:16.810+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:16.820+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:16.820+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:16.848+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:16.848+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:16.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.078 seconds
[2023-09-05T13:08:26.997+0000] {processor.py:157} INFO - Started process (PID=6261) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:27.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:27.005+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:27.003+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:27.049+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:27.067+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:27.067+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:27.093+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:27.093+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:27.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.128 seconds
[2023-09-05T13:08:30.022+0000] {processor.py:157} INFO - Started process (PID=6266) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:30.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:30.024+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:30.024+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:30.029+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:30.028+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def
      ^
SyntaxError: invalid syntax
[2023-09-05T13:08:30.030+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:30.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.042 seconds
[2023-09-05T13:08:32.146+0000] {processor.py:157} INFO - Started process (PID=6276) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:32.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:32.152+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:32.151+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:32.186+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:32.201+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:32.201+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:32.227+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:32.227+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:32.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.126 seconds
[2023-09-05T13:08:35.239+0000] {processor.py:157} INFO - Started process (PID=6281) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:35.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:35.242+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:35.241+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:35.246+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:35.244+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 13
    with DAG(
    ^
SyntaxError: invalid syntax
[2023-09-05T13:08:35.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:35.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.035 seconds
[2023-09-05T13:08:37.249+0000] {processor.py:157} INFO - Started process (PID=6286) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:37.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:37.252+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:37.251+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:37.258+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:37.256+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 13
    with DAG(
    ^
SyntaxError: invalid syntax
[2023-09-05T13:08:37.259+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:37.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.039 seconds
[2023-09-05T13:08:39.313+0000] {processor.py:157} INFO - Started process (PID=6291) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:39.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:39.314+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:39.314+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:39.330+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:39.349+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:39.349+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:39.383+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:39.383+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:39.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.124 seconds
[2023-09-05T13:08:40.506+0000] {processor.py:157} INFO - Started process (PID=6296) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:40.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:40.508+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:40.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:40.538+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:40.663+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:40.663+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:40.690+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:40.690+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:40.713+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.217 seconds
[2023-09-05T13:08:42.565+0000] {processor.py:157} INFO - Started process (PID=6301) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:42.567+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:42.571+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:42.570+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:42.611+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:42.635+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:42.635+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:42.666+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:42.666+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:42.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.137 seconds
[2023-09-05T13:08:44.563+0000] {processor.py:157} INFO - Started process (PID=6313) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:44.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:44.573+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:44.573+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:44.584+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:44.575+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 13
    with DAG(
    ^
SyntaxError: invalid syntax
[2023-09-05T13:08:44.585+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:44.643+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.084 seconds
[2023-09-05T13:08:46.562+0000] {processor.py:157} INFO - Started process (PID=6318) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:46.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:46.563+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:46.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:46.578+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:46.591+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:46.591+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:46.629+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:46.629+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:46.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.130 seconds
[2023-09-05T13:08:59.847+0000] {processor.py:157} INFO - Started process (PID=6323) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:59.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:59.851+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:59.851+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:59.857+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:59.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def
      ^
SyntaxError: invalid syntax
[2023-09-05T13:08:59.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:59.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.056 seconds
[2023-09-05T13:09:01.957+0000] {processor.py:157} INFO - Started process (PID=6333) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:01.958+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:01.961+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:01.960+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:01.965+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:01.964+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def
       ^
SyntaxError: invalid syntax
[2023-09-05T13:09:01.965+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:02.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.052 seconds
[2023-09-05T13:09:03.022+0000] {processor.py:157} INFO - Started process (PID=6338) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:03.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:03.025+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:03.025+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:03.030+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:03.029+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def gr
         ^
SyntaxError: invalid syntax
[2023-09-05T13:09:03.031+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:03.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.059 seconds
[2023-09-05T13:09:09.127+0000] {processor.py:157} INFO - Started process (PID=6343) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:09.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:09.137+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:09.135+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:09.155+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:09.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def greet
            ^
SyntaxError: invalid syntax
[2023-09-05T13:09:09.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:09.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.107 seconds
[2023-09-05T13:09:10.213+0000] {processor.py:157} INFO - Started process (PID=6348) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:10.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:10.218+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:10.217+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:10.223+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:10.221+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def greet()
              ^
SyntaxError: invalid syntax
[2023-09-05T13:09:10.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:10.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.046 seconds
[2023-09-05T13:09:13.271+0000] {processor.py:157} INFO - Started process (PID=6353) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:13.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:13.273+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:13.272+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:13.276+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:13.275+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 14
    }
    ^
SyntaxError: unmatched '}'
[2023-09-05T13:09:13.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:13.303+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.036 seconds
[2023-09-05T13:09:15.334+0000] {processor.py:157} INFO - Started process (PID=6365) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:15.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:15.338+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:15.337+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:15.362+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:15.473+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:15.473+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:09:15.492+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:15.492+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:09:15.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.197 seconds
[2023-09-05T13:09:17.561+0000] {processor.py:157} INFO - Started process (PID=6370) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:17.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:17.563+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:17.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:17.582+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:17.600+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:17.599+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:09:17.636+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:17.636+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:09:17.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.106 seconds
