[2023-09-05T13:07:02.567+0000] {processor.py:157} INFO - Started process (PID=6154) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:02.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:02.569+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:02.569+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:02.572+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:02.571+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 16
    s
    ^
SyntaxError: positional argument follows keyword argument
[2023-09-05T13:07:02.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:02.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.028 seconds
[2023-09-05T13:07:03.603+0000] {processor.py:157} INFO - Started process (PID=6159) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:03.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:03.607+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:03.606+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:03.612+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:03.610+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 17
    ) as dag:
    ^
SyntaxError: invalid syntax
[2023-09-05T13:07:03.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:03.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.042 seconds
[2023-09-05T13:07:08.667+0000] {processor.py:157} INFO - Started process (PID=6164) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:08.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:08.669+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:08.669+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:08.673+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:08.672+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 16, in <module>
    schedule=da
NameError: name 'da' is not defined
[2023-09-05T13:07:08.674+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:08.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.036 seconds
[2023-09-05T13:07:11.736+0000] {processor.py:157} INFO - Started process (PID=6169) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:11.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:11.742+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:11.741+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:11.765+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:11.756+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 572, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 217, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: <class 'datetime.datetime'> is not a valid schedule_interval.
[2023-09-05T13:07:11.765+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:11.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.079 seconds
[2023-09-05T13:07:12.801+0000] {processor.py:157} INFO - Started process (PID=6180) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:12.803+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:12.805+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:12.805+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:12.828+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:12.821+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 572, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 217, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: datetime.datetime(2023, 9, 1, 0, 0) is not a valid schedule_interval.
[2023-09-05T13:07:12.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:12.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.077 seconds
[2023-09-05T13:07:21.940+0000] {processor.py:157} INFO - Started process (PID=6186) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:21.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:21.949+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:21.947+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:21.962+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:21.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 16
    schedule
    ^
SyntaxError: positional argument follows keyword argument
[2023-09-05T13:07:21.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:22.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.088 seconds
[2023-09-05T13:07:23.975+0000] {processor.py:157} INFO - Started process (PID=6191) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:23.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:23.976+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:23.976+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:23.979+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:23.978+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 17
    ) as dag:
    ^
SyntaxError: invalid syntax
[2023-09-05T13:07:23.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:23.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.024 seconds
[2023-09-05T13:07:26.000+0000] {processor.py:157} INFO - Started process (PID=6196) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:26.001+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:26.002+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.001+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:26.015+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:26.150+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.149+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:ganza_dag_v6
[2023-09-05T13:07:26.173+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.173+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:ganza_dag_v6
[2023-09-05T13:07:26.181+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.181+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:ganza_dag_v6
[2023-09-05T13:07:26.197+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.197+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:26.208+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.208+0000] {dag.py:2929} INFO - Creating ORM DAG for ganza_dag_v6
[2023-09-05T13:07:26.218+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:26.218+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-01T00:00:00+00:00, run_after=2023-09-02T00:00:00+00:00
[2023-09-05T13:07:26.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.239 seconds
[2023-09-05T13:07:33.129+0000] {processor.py:157} INFO - Started process (PID=6206) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:33.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:33.132+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:33.131+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:33.148+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:33.159+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:33.159+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:33.181+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:33.181+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:33.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.079 seconds
[2023-09-05T13:07:45.181+0000] {processor.py:157} INFO - Started process (PID=6218) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:45.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:45.183+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:45.183+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:45.196+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:45.211+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:45.211+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:45.246+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:45.245+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:45.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.103 seconds
[2023-09-05T13:07:47.344+0000] {processor.py:157} INFO - Started process (PID=6223) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:47.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:47.350+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:47.349+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:47.377+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:47.390+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:47.390+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:47.420+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:47.419+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:47.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.114 seconds
[2023-09-05T13:07:52.396+0000] {processor.py:157} INFO - Started process (PID=6228) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:52.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:07:52.398+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:52.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:52.421+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:07:52.441+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:52.440+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:07:52.472+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:07:52.472+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:07:52.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.102 seconds
[2023-09-05T13:08:09.664+0000] {processor.py:157} INFO - Started process (PID=6238) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:09.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:09.665+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:09.665+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:09.679+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:09.788+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:09.788+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:09.819+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:09.819+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:09.848+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.189 seconds
[2023-09-05T13:08:12.759+0000] {processor.py:157} INFO - Started process (PID=6243) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:12.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:12.760+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:12.760+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:12.771+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:12.782+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:12.781+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:12.812+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:12.811+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:12.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.078 seconds
[2023-09-05T13:08:16.794+0000] {processor.py:157} INFO - Started process (PID=6256) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:16.796+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:16.797+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:16.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:16.810+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:16.820+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:16.820+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:16.848+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:16.848+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:16.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.078 seconds
[2023-09-05T13:08:26.997+0000] {processor.py:157} INFO - Started process (PID=6261) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:27.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:27.005+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:27.003+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:27.049+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:27.067+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:27.067+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:27.093+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:27.093+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:27.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.128 seconds
[2023-09-05T13:08:30.022+0000] {processor.py:157} INFO - Started process (PID=6266) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:30.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:30.024+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:30.024+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:30.029+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:30.028+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def
      ^
SyntaxError: invalid syntax
[2023-09-05T13:08:30.030+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:30.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.042 seconds
[2023-09-05T13:08:32.146+0000] {processor.py:157} INFO - Started process (PID=6276) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:32.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:32.152+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:32.151+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:32.186+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:32.201+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:32.201+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:32.227+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:32.227+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:32.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.126 seconds
[2023-09-05T13:08:35.239+0000] {processor.py:157} INFO - Started process (PID=6281) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:35.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:35.242+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:35.241+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:35.246+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:35.244+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 13
    with DAG(
    ^
SyntaxError: invalid syntax
[2023-09-05T13:08:35.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:35.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.035 seconds
[2023-09-05T13:08:37.249+0000] {processor.py:157} INFO - Started process (PID=6286) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:37.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:37.252+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:37.251+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:37.258+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:37.256+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 13
    with DAG(
    ^
SyntaxError: invalid syntax
[2023-09-05T13:08:37.259+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:37.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.039 seconds
[2023-09-05T13:08:39.313+0000] {processor.py:157} INFO - Started process (PID=6291) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:39.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:39.314+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:39.314+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:39.330+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:39.349+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:39.349+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:39.383+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:39.383+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:39.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.124 seconds
[2023-09-05T13:08:40.506+0000] {processor.py:157} INFO - Started process (PID=6296) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:40.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:40.508+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:40.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:40.538+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:40.663+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:40.663+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:40.690+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:40.690+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:40.713+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.217 seconds
[2023-09-05T13:08:42.565+0000] {processor.py:157} INFO - Started process (PID=6301) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:42.567+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:42.571+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:42.570+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:42.611+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:42.635+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:42.635+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:42.666+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:42.666+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:42.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.137 seconds
[2023-09-05T13:08:44.563+0000] {processor.py:157} INFO - Started process (PID=6313) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:44.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:44.573+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:44.573+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:44.584+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:44.575+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 13
    with DAG(
    ^
SyntaxError: invalid syntax
[2023-09-05T13:08:44.585+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:44.643+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.084 seconds
[2023-09-05T13:08:46.562+0000] {processor.py:157} INFO - Started process (PID=6318) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:46.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:46.563+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:46.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:46.578+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:46.591+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:46.591+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:08:46.629+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:46.629+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:08:46.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.130 seconds
[2023-09-05T13:08:59.847+0000] {processor.py:157} INFO - Started process (PID=6323) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:59.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:08:59.851+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:59.851+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:59.857+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:08:59.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def
      ^
SyntaxError: invalid syntax
[2023-09-05T13:08:59.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:08:59.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.056 seconds
[2023-09-05T13:09:01.957+0000] {processor.py:157} INFO - Started process (PID=6333) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:01.958+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:01.961+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:01.960+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:01.965+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:01.964+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def
       ^
SyntaxError: invalid syntax
[2023-09-05T13:09:01.965+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:02.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.052 seconds
[2023-09-05T13:09:03.022+0000] {processor.py:157} INFO - Started process (PID=6338) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:03.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:03.025+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:03.025+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:03.030+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:03.029+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def gr
         ^
SyntaxError: invalid syntax
[2023-09-05T13:09:03.031+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:03.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.059 seconds
[2023-09-05T13:09:09.127+0000] {processor.py:157} INFO - Started process (PID=6343) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:09.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:09.137+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:09.135+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:09.155+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:09.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def greet
            ^
SyntaxError: invalid syntax
[2023-09-05T13:09:09.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:09.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.107 seconds
[2023-09-05T13:09:10.213+0000] {processor.py:157} INFO - Started process (PID=6348) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:10.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:10.218+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:10.217+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:10.223+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:10.221+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 11
    def greet()
              ^
SyntaxError: invalid syntax
[2023-09-05T13:09:10.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:10.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.046 seconds
[2023-09-05T13:09:13.271+0000] {processor.py:157} INFO - Started process (PID=6353) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:13.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:13.273+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:13.272+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:13.276+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:13.275+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 14
    }
    ^
SyntaxError: unmatched '}'
[2023-09-05T13:09:13.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:13.303+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.036 seconds
[2023-09-05T13:09:15.334+0000] {processor.py:157} INFO - Started process (PID=6365) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:15.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:15.338+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:15.337+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:15.362+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:15.473+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:15.473+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:09:15.492+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:15.492+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:09:15.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.197 seconds
[2023-09-05T13:09:17.561+0000] {processor.py:157} INFO - Started process (PID=6370) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:17.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:17.563+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:17.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:17.582+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:17.600+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:17.599+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:09:17.636+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:17.636+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:09:17.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.106 seconds
[2023-09-05T13:09:47.885+0000] {processor.py:157} INFO - Started process (PID=6388) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:47.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:09:47.889+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:47.889+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:47.903+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:09:47.921+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:47.920+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:09:47.942+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:09:47.942+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:09:47.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.079 seconds
[2023-09-05T13:10:18.181+0000] {processor.py:157} INFO - Started process (PID=6405) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:10:18.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:10:18.183+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:10:18.182+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:10:18.193+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:10:18.207+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:10:18.207+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:10:18.228+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:10:18.228+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:10:18.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.070 seconds
[2023-09-05T13:10:48.440+0000] {processor.py:157} INFO - Started process (PID=6422) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:10:48.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:10:48.442+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:10:48.442+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:10:48.457+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:10:48.474+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:10:48.473+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:10:48.494+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:10:48.494+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:10:48.513+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.079 seconds
[2023-09-05T13:11:18.769+0000] {processor.py:157} INFO - Started process (PID=6439) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:18.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:18.771+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:18.771+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:18.790+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:18.809+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:18.809+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:11:18.831+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:18.831+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:11:18.850+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.088 seconds
[2023-09-05T13:11:33.980+0000] {processor.py:157} INFO - Started process (PID=6449) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:33.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:33.984+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:33.983+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:34.005+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:34.036+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:34.036+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:11:34.089+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:34.088+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:11:34.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.166 seconds
[2023-09-05T13:11:37.154+0000] {processor.py:157} INFO - Started process (PID=6454) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:37.156+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:37.158+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:37.158+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:37.169+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:37.167+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 4, in <module>
    f
NameError: name 'f' is not defined
[2023-09-05T13:11:37.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:37.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.076 seconds
[2023-09-05T13:11:48.378+0000] {processor.py:157} INFO - Started process (PID=6466) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:48.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:48.381+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:48.380+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:48.385+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:48.384+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 4
    from a
         ^
SyntaxError: invalid syntax
[2023-09-05T13:11:48.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:48.409+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.040 seconds
[2023-09-05T13:11:51.423+0000] {processor.py:157} INFO - Started process (PID=6471) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:51.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:51.428+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:51.427+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:51.437+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:51.434+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 4
    from airflow
                ^
SyntaxError: invalid syntax
[2023-09-05T13:11:51.438+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:51.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.053 seconds
[2023-09-05T13:11:54.495+0000] {processor.py:157} INFO - Started process (PID=6476) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:54.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:54.497+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:54.496+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:54.501+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:54.500+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 4
    from airflow
               ^
SyntaxError: invalid syntax
[2023-09-05T13:11:54.501+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:54.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.028 seconds
[2023-09-05T13:11:55.555+0000] {processor.py:157} INFO - Started process (PID=6481) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:55.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:55.557+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:55.556+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:55.560+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:55.559+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 4
    from airflow.
                ^
SyntaxError: invalid syntax
[2023-09-05T13:11:55.560+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:55.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.030 seconds
[2023-09-05T13:11:57.608+0000] {processor.py:157} INFO - Started process (PID=6486) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:57.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:57.614+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:57.612+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:57.625+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:57.621+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 4
    from airflow.operators
                         ^
SyntaxError: invalid syntax
[2023-09-05T13:11:57.628+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:57.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.105 seconds
[2023-09-05T13:11:59.664+0000] {processor.py:157} INFO - Started process (PID=6491) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:59.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:11:59.666+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:59.666+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:59.682+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:11:59.699+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:59.699+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:11:59.721+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:11:59.721+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:11:59.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.092 seconds
[2023-09-05T13:12:17.943+0000] {processor.py:157} INFO - Started process (PID=6508) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:17.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:17.947+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:17.946+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:17.970+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:17.965+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 23, in <module>
    tas
NameError: name 'tas' is not defined
[2023-09-05T13:12:17.972+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:18.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.072 seconds
[2023-09-05T13:12:35.208+0000] {processor.py:157} INFO - Started process (PID=6518) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:35.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:35.210+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:35.210+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:35.219+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:35.218+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 23, in <module>
    task
NameError: name 'task' is not defined
[2023-09-05T13:12:35.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:35.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.037 seconds
[2023-09-05T13:12:38.235+0000] {processor.py:157} INFO - Started process (PID=6523) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:38.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:38.236+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:38.236+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:38.243+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:38.242+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 23, in <module>
    task1
NameError: name 'task1' is not defined
[2023-09-05T13:12:38.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:38.262+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.031 seconds
[2023-09-05T13:12:39.295+0000] {processor.py:157} INFO - Started process (PID=6528) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:39.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:39.302+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:39.301+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:39.313+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:39.310+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 23
    task1 = PythonOperator(
                          ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:12:39.314+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:39.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.089 seconds
[2023-09-05T13:12:48.402+0000] {processor.py:157} INFO - Started process (PID=6540) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:48.405+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:48.407+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:48.406+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:48.416+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:48.413+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 24
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:12:48.417+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:48.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.070 seconds
[2023-09-05T13:12:50.467+0000] {processor.py:157} INFO - Started process (PID=6545) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:50.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:50.470+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:50.470+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:50.473+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:50.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 24
    t
    ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:12:50.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:50.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.048 seconds
[2023-09-05T13:12:52.542+0000] {processor.py:157} INFO - Started process (PID=6550) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:52.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:12:52.546+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:52.545+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:52.552+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:12:52.550+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 24
    task_id='first_task',
                        ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:12:52.553+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:12:52.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.043 seconds
[2023-09-05T13:13:00.609+0000] {processor.py:157} INFO - Started process (PID=6555) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:00.609+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:00.610+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:00.610+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:00.612+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:00.612+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 24
    task_id='greet',
                   ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:13:00.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:00.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.023 seconds
[2023-09-05T13:13:01.677+0000] {processor.py:157} INFO - Started process (PID=6560) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:01.679+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:01.681+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:01.680+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:01.690+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:01.687+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 25
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:13:01.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:01.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.085 seconds
[2023-09-05T13:13:04.700+0000] {processor.py:157} INFO - Started process (PID=6565) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:04.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:04.702+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:04.702+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:04.706+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:04.705+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 25
    py
     ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:13:04.707+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:04.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.032 seconds
[2023-09-05T13:13:06.771+0000] {processor.py:157} INFO - Started process (PID=6575) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:06.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:06.782+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:06.781+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:06.786+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:06.785+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 25
    python_callable=
                   ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:13:06.786+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:06.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.059 seconds
[2023-09-05T13:13:07.837+0000] {processor.py:157} INFO - Started process (PID=6580) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:07.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:07.838+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:07.838+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:07.841+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:07.840+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 25
    python_callable=greet
                        ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:13:07.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:07.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.027 seconds
[2023-09-05T13:13:12.945+0000] {processor.py:157} INFO - Started process (PID=6585) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:12.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:12.953+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:12.951+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:12.967+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:12.962+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_second_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_second_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-09-05T13:13:12.969+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:13.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.082 seconds
[2023-09-05T13:13:16.027+0000] {processor.py:157} INFO - Started process (PID=6596) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:16.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:16.033+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:16.032+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:16.082+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:16.234+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:16.233+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:13:16.254+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:16.254+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:13:16.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.263 seconds
[2023-09-05T13:13:23.144+0000] {processor.py:157} INFO - Started process (PID=6601) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:23.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:23.149+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:23.148+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:23.172+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:23.185+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:23.185+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:13:23.210+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:23.210+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:13:23.231+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.101 seconds
[2023-09-05T13:13:26.191+0000] {processor.py:157} INFO - Started process (PID=6606) to work on /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:26.194+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_second_dag.py for tasks to queue
[2023-09-05T13:13:26.196+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:26.195+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:26.221+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v6']) retrieved from /opt/airflow/dags/my_second_dag.py
[2023-09-05T13:13:26.240+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:26.239+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T13:13:26.269+0000] {logging_mixin.py:151} INFO - [2023-09-05T13:13:26.269+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v6 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T13:13:26.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_second_dag.py took 0.111 seconds
